apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd-01
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "jarvis-test"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "jarvis-test"
spec:
  destination:
    namespace: argocd-01            
    server: https://kubernetes.default.svc
  project: argocd-01-config
  source:
    path: argocd-notifications/overlays
    repoURL: https://github.com/StinkyBenji/notifications-demo
    targetRevision: master
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_K8S_ROLE
          value: vplugin
        - name: AVP_TYPE
          value: vault
        - name: AVP_VAULT_ADDR
          value: 'http://vault-server.vault.srv.cluster.local:8200'
        - name: AVP_AUTH_TYPE
          value: k8s

  