apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - notification-secret.yaml
  
patchesJson6902:
  - target:
      kind: ConfigMap
      name: argocd-notifications-cm
      version: v1
    path: patch-notification-cm.yaml